/* Inside Grey Room v12.20 — language-only pass. Gameplay untouched. */
(()=>{
 const C={
'001':'Maël Sénéchal est retrouvé mort, poignardé, dans la chambre 222. Trois personnes ont croisé sa route cette nuit-là. Leurs versions se contredisent.',
'002':'Léon s’est suicidé. Personne ne l’a tué de ses mains. Mais plusieurs personnes ont joué un rôle dans les jours qui ont précédé sa mort.',
'003':'Une attaque biologique frappe une gare. La piste mène au Centre Helios. Plusieurs décisions ont rendu la catastrophe possible.',
'004':'Sofia meurt d’une overdose après avoir appelé trois personnes à l’aide. Toutes ont reçu son appel. Aucune n’est intervenue à temps.',
'005':'Adrian Keller est retrouvé mort avec un masque blanc. Tout fait penser à un nouveau meurtre du Masque Blanc. Mais certains détails ne collent pas.',
'006':'Cinq ans après la mort de Noé dans un chalet isolé, l’affaire est rouverte. Ses anciens amis ont tous gardé le silence. Aujourd’hui, leurs versions ne concordent plus.',
'007':'Un héritage déchire une famille. Puis l’un d’eux meurt. Chacun avait quelque chose à gagner.',
'008':'Plusieurs témoins jurent de dire la vérité. Leurs versions se contredisent. Quelqu’un ment. Reste à savoir ce que chacun cherche à cacher.',
'009':'Le Sujet 17 retire son consentement. L’expérience continue quand même. Après l’incident, le médecin responsable souffre d’amnésie. Les décisions prises avant la chute restent documentées.',
'010':'Nora Weiss est retrouvée morte derrière un mur. Quelqu’un l’y a enfermée vivante. Et quelqu’un savait peut-être qu’elle était encore là.',
'011':'36 heures d’opération. Des villages détruits, des morts et des disparus. Des ordres ont été donnés, dépassés et certains faits falsifiés.',
'012':'Sacha veut quitter une communauté. Il est battu, retenu et isolé pendant près de vingt heures avant de s’échapper. Qui a ordonné ça, qui l’a fait et qui a laissé faire ?',
'013':'Le président Kessler est assassiné par un tueur payé. Le tireur est connu. Reste à découvrir qui a préparé, facilité et financé l’assassinat.',
'014':'Une fuite expose onze informateurs et leurs familles. Quelqu’un a transmis l’information. Il faut découvrir qui — et pourquoi.',
'015':'Un patient meurt dans le programme ÉLIGIBLES. Les alertes existaient. La direction a continué. Après sa mort, des dossiers sont retouchés.',
'016':'Une victime est droguée, humiliée et filmée. Plus tard, elle est retrouvée morte. La vidéo s’arrête avant le meurtre.',
'017':'Deux personnes sont enlevées. L’une meurt. L’autre ressort vivante. Ce qui s’est passé entre les deux, personne ne veut vraiment l’expliquer.',
'018':'L’ancien directeur d’un foyer abusif est retrouvé mort devant neuf assiettes vides. Chaque assiette porte un nom. Quelqu’un a voulu transformer le meurtre en message.',
'019':'Un lanceur d’alerte est retrouvé mort pendant un gala, quelques minutes avant de révéler un détournement de fonds. Plusieurs personnes avaient intérêt à l’empêcher de parler.',
'020':'327 personnes meurent dans l’incendie du Bal des Fondateurs. Certaines portes auraient encore pu être ouvertes. Il faut comprendre quelles décisions ont transformé un départ de feu en 327 morts.'};
 const txt=v=>String(v??'').replace(/\s+/g,' ').replace(/\bcanonique\b/gi,'du dossier').replace(/\btrame\b/gi,'indice').replace(/\brecontextualisation\b/gi,'nouvelle lecture').replace(/\bverrouiller\b/gi,'confirmer').replace(/\bverrouillé(e)?\b/gi,'confirmé$1').trim();
 try{SCENARIOS.forEach(s=>{if(C[s.id]){s.short=C[s.id];s.context=C[s.id];PUBLIC_LOBBY_SUMMARIES[s.id]=C[s.id]}});publicScenarioSummary=id=>C[id]||scenario(id).short;canonicalBriefingText=id=>C[id]||scenario(id).context}catch{}
 try{
  Object.assign(ROLE_INFO.enqueteur,{win:'Reconstitue les faits et attribue la bonne responsabilité à chacun.',body:'Tu mènes les interrogatoires et rends le verdict final.'});
  Object.assign(ROLE_INFO.analyste,{win:'Aide à reconstruire les faits sans te laisser piéger par les apparences.',body:'Tu repères les contradictions et aides l’Enquêteur.'});
  Object.assign(ROLE_INFO.suspect,{win:'Fais reconnaître exactement ce que tu as fait — ni plus, ni moins.',body:'Tu peux mentir, minimiser, accuser ou avouer une partie. Tu n’inventes jamais une preuve.'});
  Object.assign(ROLE_INFO.maitre,{label:'Avocat',win:'Évite que tes clients soient accusés de faits qu’ils n’ont pas commis.',body:'Tu défends tes clients. Tu argumentes, tu n’inventes pas.'});
  Object.assign(ROLE_INFO.procureur,{win:'Fais reconnaître les responsabilités sans accuser au-delà des faits.',body:'Tu peux mener des entretiens ciblés et mettre les versions sous pression.'});
  Object.assign(ROLE_INFO.juge,{win:'Rends le bon jugement sans dépasser tes accès confidentiels.',body:'Tu peux ouvrir certaines informations protégées et rendre ton propre jugement.'});
  Object.assign(ROLE_INFO.journaliste,{win:'Publie les bonnes informations sans perdre ta crédibilité.',body:'Tu peux publier une Breaking News par cycle et envoyer des messages privés.'});
  Object.assign(ROLE_INFO.inspecteur,{win:'Choisis les bonnes pistes et établis les faits matériels importants.',body:'Tu peux mener une action de terrain par cycle.'});
  Object.assign(ROLE_INFO.expert,{win:'Interprète correctement les preuves techniques.',body:'Tu peux lancer une analyse par cycle. Tu établis des faits, pas un coupable.'});
  Object.assign(ROLE_INFO.temoin,{win:'Reste cohérent avec ce que tu sais réellement.',body:'Tu peux être entendu puis devenir personne d’intérêt.'});
  Object.assign(ROLE_INFO.espion,{win:'Accomplis ta mission sans être démasqué.',body:'Ton rôle public est une couverture. Tu n’inventes jamais de preuve.'});
 }catch{}
 try{RULES.splice(0,RULES.length,
  {title:'1. Le principe',items:['Les faits du dossier ne changent jamais.','Les rôles n’ont pas tous les mêmes informations.','Tu peux défendre une version. Tu ne peux jamais inventer une preuve.']},
  {title:'2. Ta carte',items:['Lis ta carte seul.','Ce qui est écrit sur ta carte est vrai.','Si ton rôle l’autorise, tu peux mentir à l’oral.']},
  {title:'3. Déroulement',items:['Lecture des cartes : environ 5 min.','Premier échange Enquêteur + Analyste : 3 min.','Maximum 3 cycles. Un interrogatoire dure jusqu’à 8 min.','Entre les cycles, le MJ peut transmettre de nouveaux indices.']},
  {title:'4. MJ automatique',items:['L’Enquêteur et l’Analyste répondent à deux questions courtes.','Le MJ choisit seulement parmi des indices déjà écrits.','Il peut ajuster le rythme. Il ne change jamais la vérité.']},
  {title:'5. Communications',items:['Le Canal Enquête est réservé aux rôles autorisés.','Pendant un interrogatoire, l’Enquêteur peut activer un flux vidéo + audio en direct. Aucun enregistrement, aucun replay.','Une coupure confidentielle de 60 secondes maximum est disponible une fois par cycle.']},
  {title:'6. Fin de partie',items:['Quand l’enquête se ferme, aucun nouvel indice n’arrive.','Les suspects accusés ont une dernière défense.','Chacun confirme ensuite son choix final avant la révélation.']},
  {title:'7. Responsabilité',items:['Un suspect peut avoir fait quelque chose de grave sans être le meurtrier.','Juge les faits, pas l’impression laissée par le joueur.','Un comportement étrange n’est jamais une preuve à lui seul.']}
 )}catch{}
 try{phaseLabel=ph=>({briefing:'OUVERTURE DU DOSSIER',role_reading:'LECTURE PRIVÉE',initial_debrief:'PREMIER POINT',interrogation_select:'PROCHAIN INTERROGATOIRE',interrogation:'INTERROGATOIRE',cycle_debrief:'POINT D’ENQUÊTE',annex_inspecteur:'ACTION TERRAIN',annex_procureur:'ENTRETIEN PROCUREUR',annex_juge:'DÉCISION DU JUGE',annex_temoin:'TÉMOINS',annex_journaliste:'JOURNALISTE',annex_expert:'EXPERTISE',trame:'NOUVEL INDICE',closed:'ENQUÊTE TERMINÉE',provisional_orals:'PREMIÈRES CONCLUSIONS',provisional_lock:'PREMIÈRES ACCUSATIONS',defense:'DERNIÈRES DÉFENSES',final_debrief:'DERNIER POINT',locking:'VERDICT FINAL',reveal:'VÉRITÉ'})[ph]||String(ph||'PARTIE').toUpperCase()}catch{}
 try{phaseInstruction=(role,ph,target)=>{
  const n=target?.pseudo?h(target.pseudo):'la personne appelée';
  if(ph==='role_reading')return'<p>Lis ta carte. Garde-la pour toi.</p>';
  if(ph==='initial_debrief')return['enqueteur','analyste'].includes(role)?'<p>3 min. Mettez vos premières hypothèses en commun.</p>':'<p>Prépare ta version.</p>';
  if(ph==='interrogation_select')return role==='enqueteur'?'<p>Choisis la prochaine personne à interroger.</p>':'<p>L’Enquêteur choisit qui passe ensuite.</p>';
  if(ph==='interrogation'){if(target?.id===STATE?.sync?.player?.id)return'<p><b>Tu es interrogé.</b> Réponds avec ta carte. Tu peux mentir si ton rôle le permet. N’invente jamais une preuve.</p>';if(role==='enqueteur')return`<p>Interroge <b>${n}</b>. Va droit aux faits.</p>`;if(role==='analyste')return'<p>Observe. Note les contradictions et les changements de version.</p>';return'<p>Interrogatoire en cours.</p>'}
  if(ph==='cycle_debrief')return['enqueteur','analyste'].includes(role)?'<p>Deux questions. Elles règlent le rythme, pas l’enquête.</p>':'<p>L’Enquêteur et l’Analyste font le point.</p>';
  if(ph==='trame'){const e=latestEvent?.('trame');const card=e&&canInvestigationChannel?.(role)?`<div class="trame-focus"><b>${h(txt(e.payload?.title||'NOUVEL INDICE'))}</b><span>${h(txt(e.payload?.text||''))}</span></div>`:'';return`<p>Nouvel indice. Lis-le. À vous d’en tirer quelque chose.</p>${card}`}
  if(ph==='closed')return'<p><b>L’enquête est terminée.</b> Il n’y aura plus aucun indice. Vous devez maintenant décider.</p>';
  if(ph==='provisional_lock')return role==='enqueteur'?'<p>Attribue un niveau à chaque suspect. Ces accusations décideront qui doit se défendre.</p>':'<p>L’Enquêteur fixe ses premières accusations.</p>';
  if(ph==='final_debrief')return'<p>3 min. Dernier échange. Aucun nouveau fait n’arrivera.</p>';
  if(ph==='locking')return'<p>Fin des échanges. Confirme ton choix final. Après ça, impossible de revenir en arrière.</p>';
  if(ph==='reveal')return'<p>Le verdict est fermé. Voici ce qui s’est vraiment passé.</p>';
  return'<p>La partie continue.</p>'
 }}catch{}
 try{privateCardHtml=()=>{const d=STATE.sync,p=d.player,ps=p.private_state||{},pub=p.public_role,secret=p.secret_role,info=roleInfo(secret==='espion'?'espion':pub),sus=pub==='suspect';return`<div class="private-card-v11"><div class="kicker">CARTE PRIVÉE · NE LA MONTRE À PERSONNE</div><h2>${h(displayRole(pub,p.pseudo||STATE.playerPseudo))}</h2><div class="role-summary"><b>TON OBJECTIF</b><span>${h(info.win)}</span></div>${valueBlock(sus?'QUI TU ES':'TON RÔLE',txt(ps.place))}${valueBlock(sus?'CE QUE TU AS FAIT':'CE QUI S’EST PASSÉ',txt(ps.chronology))}${valueBlock(sus?'CE QUE TU CACHES':'CE QUE TU GARDES POUR TOI',txt(ps.hide),'danger-soft')}${valueBlock('CE QUE TU SAIS',txt(ps.anchors))}${valueBlock('TES RELATIONS',ps.relations)}${valueBlock('TES CLIENTS',ps.clients)}${valueBlock(sus?'TA DÉFENSE':'TA LIGNE',txt(ps.position))}${secret==='espion'?valueBlock('MISSION SECRÈTE',txt(ps.secret_mission),'secret-alert'):''}<div class="private-foot">Cette carte dit ce qui est vrai. Tu peux mentir si ton rôle le permet. Tu ne peux jamais inventer une preuve, un lieu ou un événement.</div></div>`}}catch{}
 try{renderDebriefForm=()=>myAction('debrief')?'<div class="locked-state">Réponses envoyées.</div>':`<div class="qcm-v11 narrative-debrief gameplay-simple-debrief"><div class="narrative-debrief-intro"><b>POINT D’ENQUÊTE · 2 QUESTIONS</b><span>Le MJ règle le rythme. Il ne change pas les faits.</span></div><div class="field"><label for="qConvergence">Vous êtes déjà d’accord sur une piste ?</label><select id="qConvergence"><option value="0">Non</option><option value="1">Un peu</option><option value="2">Oui</option></select></div><div class="field"><label for="qConfusion">Vous êtes encore perdus ?</label><select id="qConfusion"><option value="0">Non</option><option value="1">Un peu</option><option value="2">Oui</option></select></div><button class="btn primary block" onclick="submitDebrief()">Envoyer</button></div>`}catch{}
 try{responsibilityLabel=l=>({0:'Aucune responsabilité',1:'Secondaire',2:'Importante',3:'Centrale'})[+l]||'Non renseignée';levelsForm=(p='lvl')=>STATE.sync.suspects.map(s=>`<div class="level-row"><span>${h(s.pseudo)}</span><select id="${p}_${s.id}"><option value="0">0 · aucune responsabilité</option><option value="1">1 · secondaire</option><option value="2">2 · importante</option><option value="3">3 · centrale</option></select></div>`).join('');renderProvisionalForm=()=>myAction('provisional')?'<div class="locked-state">Premières accusations confirmées.</div>':`<div class="action-section"><h3>Que reproches-tu à chacun ?</h3>${levelsForm('prov')}<button class="btn danger block" onclick="setProvisional()">Confirmer mes accusations</button></div>`}catch{}
 try{renderReveal=()=>{const e=latestEvent('reveal'),p=e?.payload||{},t=STATE.sync.scenario.truth||{},r=p.responsibilities||[],sum=revealSummaryWithNames(t.summary||p.summary||'',r),cine=t.cinematic||{};return`<div class="reveal-v11 cold-reveal"><div class="kicker">RÉVÉLATION</div><h2>Voici ce qui s’est vraiment passé.</h2><section><small>ACTE I</small><h3>Votre verdict</h3>${r.map(x=>`<div class="responsibility"><b>${h(x.pseudo)}</b><span>${x.enqueteur_level<0?'Non évalué':`${x.enqueteur_level}/3 · ${h(responsibilityLabel(x.enqueteur_level))}`}</span></div>`).join('')}</section><section><small>ACTE II</small><h3>La vérité</h3><p>${h(txt(sum))}</p>${r.map(x=>`<div class="responsibility"><b>${h(x.pseudo)}</b><span>${x.truth_level}/3 · ${h(responsibilityLabel(x.truth_level))}</span><small>${h(responsibilityDelta(x.truth_level,x.enqueteur_level))}</small></div>`).join('')}</section>${Array.isArray(cine.timeline)&&cine.timeline.length?`<section><small>ACTE III</small><h3>Ce qui s’est passé</h3><ol>${cine.timeline.map(x=>`<li>${h(txt(x))}</li>`).join('')}</ol></section>`:''}${Array.isArray(cine.characters)&&cine.characters.length?`<section><small>ACTE IV</small><h3>Ce que chacun cachait</h3>${cine.characters.map((c,i)=>`<div class="cold-char"><h3>${h(r[(+c.slot||i+1)-1]?.pseudo||`Suspect ${+c.slot||i+1}`)}</h3>${c.place?`<b>QUI TU ES</b><p>${h(txt(c.place))}</p>`:''}${c.chronology?`<b>CE QUE TU AS FAIT</b><p>${h(txt(c.chronology))}</p>`:''}${c.hide?`<b>CE QUE TU CACHAIS</b><p>${h(txt(c.hide))}</p>`:''}${c.anchors?`<b>CE QUE TU SAVAIS</b><p>${h(txt(c.anchors))}</p>`:''}</div>`).join('')}</section>`:''}<div class="result-list">${(p.results||[]).map(x=>`<div class="result-line ${x.success?'winner':'loser'}"><b>${h(x.pseudo)} · ${h(publicRoleLabel(x.role))}</b><strong>${x.success?'VICTOIRE':'DÉFAITE'}</strong><span>${h(txt(x.text))}</span></div>`).join('')}</div>${renderContinuationPanel()}<button class="btn block" onclick="leaveRoom()">Quitter la cellule</button></div>`}}catch{}
 const st=document.createElement('style');st.textContent='.cold-reveal{display:grid;gap:14px}.cold-reveal section{padding:16px;border:1px solid rgba(255,255,255,.08);border-radius:16px}.cold-reveal section>small,.cold-char>b{font:800 8px "IBM Plex Mono",monospace;letter-spacing:.13em;color:#78838c}.cold-reveal section>h3{margin:6px 0 12px}.cold-reveal section p,.cold-reveal li{line-height:1.55;color:#c8cfd4}.cold-reveal ol{padding-left:22px}.cold-char{padding:13px 0;border-top:1px solid rgba(255,255,255,.07)}.cold-char h3{margin:0 0 10px}.cold-char p{margin:4px 0 10px}';document.head.appendChild(st);
})();