/* Inside Grey Room v12.21 — player-facing rules. No gameplay logic. */
(()=>{
 const FR=[
  {title:'1. Le cœur du jeu',items:['Inside Grey Room est une enquête psychologique à informations cachées. La vérité du dossier est fixe, mais personne ne la possède entièrement.','Le but n’est pas seulement de trouver « un coupable » : il faut comprendre qui a fait quoi, ce que chacun savait et jusqu’où va sa responsabilité.','Le jeu récompense la précision. Accuser trop fort peut être aussi mauvais que passer à côté d’un fait essentiel.']},
  {title:'2. Ta carte est ta réalité',items:['Lis ta carte seul et ne montre jamais ton écran ou ta carte privée aux autres joueurs.','Tout fait écrit sur ta carte est vrai dans le dossier. Tu peux cacher, minimiser, détourner ou mentir à l’oral si ton rôle le permet.','Tu ne peux jamais inventer une preuve, un lieu, un message, un témoin ou un événement qui n’existe pas dans ta carte ou dans le dossier.']},
  {title:'3. Enquêter sous pression',items:['La partie avance en cycles limités : interrogatoires, échanges, actions de rôles et nouveaux indices. Le temps fait partie du jeu.','Un indice ouvre une piste ; il ne donne pas la solution. Cherche les convergences entre chronologie, traces, contradictions, accès et motivations.','Le comportement d’un joueur n’est jamais une preuve. Juge le dossier, pas le talent d’acteur.']},
  {title:'4. Rôles et pouvoirs',items:['Chaque rôle possède une manière différente d’agir, de savoir et de gagner. Un pouvoir ouvre une possibilité ; il ne garantit jamais la vérité.','Utilise les actions spéciales uniquement lorsqu’elles sont disponibles dans l’interface. Si le système bloque une action, elle n’est pas disponible à ce moment-là.','Un rôle secret peut modifier tes intérêts sans changer les faits du dossier.']},
  {title:'5. Parler, bluffer, convaincre',items:['Défends ta version avec ce que ton personnage sait. Le bluff est permis lorsqu’il respecte ta carte ; fabriquer de faux éléments de preuve ne l’est pas.','Les canaux privés et publics font partie de l’enquête. N’utilise pas de moyen extérieur pour contourner les informations cachées.','Ne transforme pas le jeu en attaque personnelle : on met les versions sous pression, pas les joueurs.']},
  {title:'6. Quand l’enquête se ferme',items:['Une fois l’enquête close, aucun nouvel indice ni nouvelle analyse ne vient sauver une mauvaise lecture.','Les personnes formellement accusées disposent d’une dernière défense, puis les choix finaux sont confirmés.','La révélation compare vos décisions à la vérité du dossier et mesure la justesse de votre responsabilité, pas seulement un nom trouvé au hasard.']},
  {title:'7. L’esprit Grey Room',items:['Doute de ce qui paraît évident. Une contradiction peut cacher un crime, une peur, une loyauté ou simplement une autre faute.','Cherche une reconstruction cohérente plutôt qu’une histoire spectaculaire. Les faits ont toujours priorité sur l’intuition.','Joue pour comprendre la pièce entière — même lorsque ton propre rôle a intérêt à ce que les autres n’en voient qu’une partie.']}
 ];
 const EN=[
  {title:'1. The core of the game',items:['Inside Grey Room is a psychological investigation built on hidden information. The case truth is fixed, but nobody holds all of it.','The goal is not simply to find “a culprit”: work out who did what, what each person knew and how far their responsibility goes.','Precision matters. Over-accusing can be as costly as missing an essential fact.']},
  {title:'2. Your card is your reality',items:['Read your card alone. Never show your screen or private card to another player.','Every fact written on your card is true in the case. You may hide, minimise, redirect or lie verbally when your role allows it.','Never invent evidence, a place, a message, a witness or an event that does not exist on your card or in the case.']},
  {title:'3. Investigate under pressure',items:['The game moves through limited cycles: interrogations, discussion, role actions and new leads. Time is part of the game.','A lead opens a path; it never gives the solution. Look for convergence between chronology, traces, contradictions, access and motives.','A player’s behaviour is never evidence. Judge the case, not acting ability.']},
  {title:'4. Roles and powers',items:['Every role has a different way to act, know and win. A power opens an opportunity; it never guarantees the truth.','Use special actions only when the interface makes them available. If the system blocks an action, it is not available at that moment.','A secret role can change your interests without changing the facts of the case.']},
  {title:'5. Talk, bluff, convince',items:['Defend your version using what your character knows. Bluffing is allowed when it respects your card; fabricating evidence is not.','Private and public channels are part of the investigation. Do not use outside communication to bypass hidden information.','Do not turn the game into a personal attack: put versions under pressure, not players.']},
  {title:'6. When the investigation closes',items:['Once the investigation is closed, no new lead or analysis will rescue a bad reading.','Formally accused players receive a final defence, then final choices are confirmed.','The reveal compares your decisions with the case truth and measures how accurately you judged responsibility — not whether you guessed one name.']},
  {title:'7. The Grey Room mindset',items:['Question what looks obvious. A contradiction may hide a crime, fear, loyalty or simply a different wrongdoing.','Build a coherent reconstruction rather than the most dramatic story. Facts always outrank intuition.','Play to understand the whole room — even when your own role benefits from others seeing only part of it.']}
 ];
 const active=()=>window.IGR_LOCALE==='en'?EN:FR;
 const list=()=>`<div class="rule-list">${active().map(r=>`<div class="rule"><h3>${h(r.title)}</h3><p>${r.items.map(i=>`• ${h(i)}`).join('<br>')}</p></div>`).join('')}</div>`;
 try{renderRules=function(){const en=window.IGR_LOCALE==='en';byId('app').innerHTML=shell(`<main class="page"><div class="page-head"><div><div class="kicker">${en?'Rules':'Règles'}</div><h1>${en?'How to enter the Grey Room':'Entrer dans la Grey Room'}</h1></div><button class="btn ghost small" onclick="goHome()">← ${en?'Home':'Accueil'}</button></div><section class="panel">${list()}</section></main>`)}}catch(_){}
 try{const base=renderGameTab;renderGameTab=function(){if(STATE.tab==='rules')return list();return base.apply(this,arguments)}}catch(_){}
})();
