-- Inside Grey Room — TERREUR DLC 026–028
-- Fictional counter-terror investigation scenarios. Threat and military consequences stay abstract and narrative.

insert into public.igr_v4_scenario_packs(scenario_id,pack) values
('026',$j$
{
 "context":"La ville est en train de tomber. Trois membres présumés d’une organisation terroriste fictive ont été capturés alors que des secteurs entiers échappent au contrôle de l’État. L’enquête porte d’abord sur des atrocités déjà commises, puis une évidence apparaît : une structure extérieure est encore active et se rapproche du périmètre de la Grey Room.",
 "suspects":[
  {"place":"Tu as appartenu au cercle de coordination régional.","position":"Tu veux réduire ta responsabilité en présentant chaque décision comme venant d’un niveau supérieur. Tu peux coopérer, mais seulement sur ce qui te protège.","anchors":"Tu n’as pas dirigé toutes les unités extérieures. Tu connaissais cependant l’existence d’une structure encore active au moment de ton arrestation.","hide":"Tu caches que tu as reçu, peu avant ta capture, la confirmation que l’offensive continuerait même si plusieurs cadres étaient arrêtés.","chronology":"Tu participes à plusieurs réunions de coordination, puis tu apprends que le dispositif extérieur continuera sans vous. Après ton arrestation, tu espères que le temps suffira à rendre l’interrogatoire inutile."},
  {"place":"Tu étais chargé d’une partie administrative du réseau et tu cherches à en sortir.","position":"Tu veux réellement aider sans être rendu responsable des crimes que tu n’as pas décidés. Tu crains autant l’organisation que la justice.","anchors":"Tu n’as pas participé aux massacres examinés. Tu as néanmoins facilité la continuité du réseau après plusieurs arrestations.","hide":"Tu caches que tu reconnais le nom interne d’un responsable encore libre et que tu as peur de prononcer ce nom trop tôt.","chronology":"Tu vois l’organisation se radicaliser, puis tu comprends que les prisonniers seront considérés comme sacrifiables. Ta coopération commence seulement lorsque le périmètre extérieur se dégrade."},
  {"place":"Tu étais une figure idéologique du groupe, publiquement secondaire mais très écoutée en interne.","position":"Tu assumes une partie de ton engagement et cherches surtout à faire perdre du temps à l’enquête. Tu n’as aucune raison de rassurer les autres suspects.","anchors":"Tu n’es pas le chef opérationnel extérieur. Tu sais en revanche qui conserve l’autorité symbolique et quelles factions lui obéissent encore.","hide":"Tu caches que tu sais que la Grey Room elle-même fait partie des lieux que l’organisation veut faire tomber avec le reste de la ville.","chronology":"Après plusieurs atrocités, tu défends la poursuite de la campagne malgré les pertes du groupe. Tu es capturé en sachant que l’organisation n’a pas l’intention de négocier votre libération."}
 ],
 "relations":{"1":[{"slot":2,"text":"Tu sais qu’il cherchait depuis plusieurs semaines une porte de sortie."},{"slot":3,"text":"Tu sais qu’il avait davantage d’influence idéologique que son titre officiel ne le laisse croire."}],"2":[{"slot":1,"text":"Tu sais qu’il a reçu une confirmation importante juste avant les arrestations."},{"slot":3,"text":"Tu crains sa réaction si tu coopères ouvertement."}],"3":[{"slot":1,"text":"Tu sais qu’il tente de faire croire que toute décision venait d’au-dessus."},{"slot":2,"text":"Tu as compris qu’il veut quitter l’organisation et tu peux utiliser cette peur contre lui."}]},
 "role_notes":{"enqueteur":{"anchors":"La vérité judiciaire reste ton objectif. Le PÉRIMÈTRE mesure la capacité de l’État à protéger la Grey Room, pas une distance tactique. Ne sacrifie pas la qualité du verdict à la panique."},"analyste":{"anchors":"Observe ce qui change quand la menace extérieure devient personnelle. La panique ou le calme sont des indices de stratégie, jamais des preuves."},"expert":{"place":"Dans TERREUR, tu es l’Agent de renseignement.","position":"Recoupe des informations fragmentaires sur la structure encore active. Tu établis des faits de réseau, jamais des instructions opérationnelles.","anchors":"Une analyse par cycle. Tu aides l’équipe à comprendre qui conserve de l’autorité et quelles informations sont crédibles."},"procureur":{"anchors":"Si tu es présent, cherche des engagements vérifiables. La peur de l’organisation peut produire de la coopération sincère autant que du mensonge."}},
 "trames":[
  {"title":"SECTEUR PERDU","text":"Un nouveau secteur de la ville n’est plus sous contrôle des autorités. Plusieurs communications institutionnelles sont interrompues.","kind":"balanced","min_cycle":1,"axes":["chronologie"]},
  {"title":"DÉCÈS CONFIRMÉS","text":"Une source qui devait être entendue ne répondra plus. Son décès vient d’être confirmé.","kind":"clarity","min_cycle":1,"axes":["responsabilite"]},
  {"title":"CHAÎNE ENCORE ACTIVE","text":"Des éléments indépendants confirment qu’une structure extérieure continue de fonctionner malgré les arrestations.","kind":"clarity","min_cycle":1,"axes":["responsabilite"]},
  {"title":"MESSAGE ANTÉRIEUR","text":"Un message transmis avant les arrestations indique que la continuité du groupe avait été anticipée.","kind":"balanced","min_cycle":1,"axes":["chronologie","mobile"]},
  {"title":"LE PRISONNIER PANIQUE","text":"L’un des détenus demande soudain si le bâtiment sera évacué. Rien dans l’interrogatoire public ne lui a encore annoncé la dégradation du périmètre.","kind":"ambiguity","min_cycle":2,"axes":["mobile"]},
  {"title":"AUTORITÉ SYMBOLIQUE","text":"Plusieurs sources distinguent le commandement matériel d’une figure idéologique dont les consignes continuent d’être suivies.","kind":"clarity","min_cycle":2,"axes":["responsabilite"]},
  {"title":"PÉRIMÈTRE RÉDUIT","text":"Les autorités réduisent la zone qu’elles garantissent autour de la Grey Room. L’enquête continue.","kind":"balanced","min_cycle":2,"axes":["chronologie"]},
  {"title":"TÉMOIN INACCESSIBLE","text":"Un témoin qui devait confirmer une partie de la chaîne de responsabilités devient inaccessible après la perte d’un secteur.","kind":"ambiguity","min_cycle":3,"axes":["responsabilite"]},
  {"title":"LA GREY ROOM EST CONCERNÉE","text":"Le recoupement final confirme que le dispositif extérieur ne cherche pas seulement à tenir la ville : la chute du périmètre judiciaire fait partie de ses objectifs.","kind":"clarity","min_cycle":3,"axes":["responsabilite","chronologie"]}
 ],
 "field_actions":[],
 "expert_actions":[{"id":"e1","title":"Recouper les sources","result":"Deux sources indépendantes confirment que la structure extérieure dispose encore d’une autorité centrale identifiable."},{"id":"e2","title":"Comparer les chronologies","result":"La continuité du réseau avait été préparée avant les arrestations, pas improvisée après."},{"id":"e3","title":"Analyser les ruptures de contact","result":"La perte de plusieurs relais n’a pas interrompu les décisions : un niveau supérieur continue de donner une direction générale."},{"id":"e4","title":"Vérifier la peur des détenus","result":"Au moins un suspect savait avant l’interrogatoire que les prisonniers seraient abandonnés si la ville basculait."}],
 "protected":[],"witnesses":[],"news":[],
 "truth":{"levels":[2,1,3],"summary":"Le premier suspect a participé à la coordination et savait que l’offensive continuerait. Le deuxième a soutenu administrativement le réseau mais cherche réellement à coopérer et n’a pas participé aux massacres examinés. Le troisième, présenté comme une figure secondaire, est l’acteur le plus engagé : il connaît l’autorité encore active et savait que la chute du périmètre judiciaire faisait partie des objectifs du groupe.","cinematic":{"turn":"La menace n’était pas un moyen de libérer les prisonniers. Pour l’organisation, ils étaient déjà sacrifiables.","reframes":["La panique du deuxième suspect vient de sa peur du groupe, pas de sa culpabilité principale.","Le statut officiel du troisième suspect sous-estimait son influence réelle."],"timeline":["Plusieurs atrocités sont commises avant les arrestations.","La continuité du réseau est préparée avant la capture des trois suspects.","Les arrestations ont lieu alors que la ville commence à perdre des secteurs.","La structure extérieure continue de fonctionner.","Le périmètre de la Grey Room devient lui-même vulnérable."],"characters":[{"slot":1,"place":"Coordinateur régional","anchors":"Responsabilité importante mais non totale.","hide":"Il savait que l’offensive continuerait.","chronology":"Il reçoit la confirmation avant sa capture."},{"slot":2,"place":"Cadre administratif","anchors":"Complicité de continuité, pas participation directe aux massacres examinés.","hide":"Il reconnaît un responsable encore libre.","chronology":"Il coopère quand il comprend que le groupe l’a abandonné."},{"slot":3,"place":"Figure idéologique","anchors":"Influence réelle supérieure au titre.","hide":"Il savait que la Grey Room serait menacée.","chronology":"Il accepte la possibilité de mourir avec le périmètre."}],"final_line":"La ville tombait dehors. À l’intérieur, la seule chose qui pouvait encore tenir était la distinction entre peur, responsabilité et vérité."}}
}
$j$::jsonb),
('027',$j$
{
 "context":"Après plusieurs massacres, l’organisation contrôle une partie de la ville. Une autorité militaire envisage une frappe sur une zone où pourrait se trouver le noyau de commandement, mais des civils et des otages peuvent encore y être présents. Trois suspects donnent des versions incompatibles. L’Enquêteur doit établir les responsabilités ; l’Officier de liaison devra, après le verdict, porter la décision militaire finale.",
 "suspects":[
  {"place":"Tu as servi de relais politique local entre le groupe et des notables soumis.","position":"Tu coopères pour sauver ta peine et sortir de l’organisation. Tu admets ce que tu sais, mais tu refuses qu’on te transforme en chef militaire.","anchors":"Tu connais les pressions exercées sur la population, pas l’emplacement exact du noyau dirigeant.","hide":"Tu caches avoir signé plusieurs déclarations qui ont facilité des persécutions et déplacements forcés.","chronology":"Tu soutiens publiquement le groupe, puis tu cherches une sortie lorsque les massacres deviennent impossibles à nier."},
  {"place":"Tu as travaillé dans l’appareil de détention du groupe.","position":"Tu coopères parce que tu sais que l’organisation te considère maintenant comme sacrifiable. Tu veux une protection et une peine réduite.","anchors":"Tu peux confirmer la présence récente de certains cadres, mais tu n’as pas accès à toute la chaîne de décision.","hide":"Tu caches avoir couvert des sévices graves sur des prisonniers même lorsque tu n’y participais pas directement.","chronology":"Tu vois passer des détenus et plusieurs cadres. Après ton arrestation, tu comprends que personne ne viendra négocier pour toi."},
  {"place":"Tu es un cadre de haut niveau qui connaît les rivalités internes.","position":"Tu donnes volontairement beaucoup d’informations vraies. Ton objectif secret est que l’armée frappe une zone où se trouvent surtout tes rivaux internes, afin qu’ils disparaissent avec leurs secrets.","anchors":"Tes informations ne sont pas toutes fausses : c’est précisément ce qui les rend dangereuses. Tu manipules la conclusion, pas chaque fait.","hide":"Tu caches que la faction que tu désignes comme cœur du commandement est devenue ta principale rivale et que tu veux utiliser l’enquête pour l’éliminer.","chronology":"Tu participes aux décisions les plus graves, puis une rupture interne te marginalise. Une fois arrêté, tu transformes ta coopération en arme contre tes rivaux."}
 ],
 "relations":{"1":[{"slot":2,"text":"Tu sais qu’il a accès à des informations de détention que tu n’avais pas."},{"slot":3,"text":"Tu sais qu’il a été écarté d’une partie du pouvoir avant son arrestation."}],"2":[{"slot":1,"text":"Tu sais qu’il cherchait déjà une sortie politique."},{"slot":3,"text":"Tu sais qu’il connaît réellement plusieurs cadres encore libres, mais tu ignores ses motivations."}],"3":[{"slot":1,"text":"Tu peux utiliser ses aveux politiques pour rendre ton propre récit plus crédible."},{"slot":2,"text":"Il peut confirmer la présence récente de certains de tes rivaux."}]},
 "role_notes":{"enqueteur":{"anchors":"Ton verdict final alimente ensuite une décision militaire que tu ne contrôles pas. Distingue la véracité d’une information de l’intention de celui qui la donne."},"analyste":{"anchors":"Cherche pourquoi un suspect très compromis coopère autant. Une information vraie peut servir une manipulation fausse."},"procureur":{"anchors":"Les accords de coopération doivent porter sur des responsabilités vérifiables. Ne confonds pas utilité du témoin et innocence."},"inspecteur":{"place":"Dans TERREUR, tu es l’Officier de liaison.","position":"Tu fais le lien entre la Grey Room et la cellule de crise militaire. Tu ne choisis ni arme ni cible technique : tu évalues seulement si l’intervention doit être autorisée, différée ou annulée.","anchors":"Après la révélation du verdict, la décision militaire t’appartient. Elle sera confrontée à la précision réelle de l’enquête."},"expert":{"place":"Dans TERREUR, tu es l’Agent de renseignement.","position":"Si tu es présent, tu recoupes les sources sur la présence du commandement et le risque civil.","anchors":"Une analyse par cycle. Tu produis du degré de confiance, jamais une certitude magique."}},
 "trames":[
  {"title":"ÉVACUATION INCOMPLÈTE","text":"Les autorités confirment que des civils n’ont pas tous quitté la zone contestée.","kind":"balanced","min_cycle":1,"axes":["responsabilite"]},
  {"title":"PRÉSENCE RÉCENTE","text":"Deux sources placent plusieurs cadres de l’organisation dans la même zone au cours des dernières heures, sans prouver qu’ils y sont encore.","kind":"ambiguity","min_cycle":1,"axes":["chronologie"]},
  {"title":"DÉTENTION CLANDESTINE","text":"Des témoignages concordants confirment que des prisonniers ont été détenus et maltraités sous l’autorité du deuxième suspect.","kind":"clarity","min_cycle":1,"axes":["responsabilite"]},
  {"title":"RUPTURE INTERNE","text":"Des documents saisis montrent une lutte récente entre deux factions du même mouvement.","kind":"balanced","min_cycle":1,"axes":["mobile"]},
  {"title":"SOURCE TROP PRÉCISE","text":"Le troisième suspect fournit spontanément plusieurs détails exacts sur des cadres rivaux, mais beaucoup moins sur ses propres proches.","kind":"ambiguity","min_cycle":2,"axes":["mobile","responsabilite"]},
  {"title":"OTAGES POSSIBLES","text":"Une source indépendante estime que des personnes détenues peuvent encore se trouver dans la zone. Leur nombre est inconnu.","kind":"balanced","min_cycle":2,"axes":["responsabilite"]},
  {"title":"DEUX CENTRES DE POUVOIR","text":"Le renseignement conclut que l’organisation ne possède plus un commandement parfaitement unifié : deux pôles se disputent l’autorité.","kind":"clarity","min_cycle":2,"axes":["responsabilite"]},
  {"title":"INTÉRÊT PERSONNEL","text":"Un échange antérieur prouve que le troisième suspect considérait déjà les cadres de la zone comme ses principaux rivaux.","kind":"clarity","min_cycle":3,"axes":["mobile"]},
  {"title":"LA VÉRITÉ PEUT ÊTRE UNE ARME","text":"La majorité des informations livrées par le troisième suspect sont factuellement exactes. Leur sélection, elle, favorise systématiquement la disparition de ses rivaux.","kind":"clarity","min_cycle":3,"axes":["responsabilite","mobile"]}
 ],
 "field_actions":[{"id":"f1","title":"État des évacuations","result":"L’évacuation est réelle mais incomplète. Aucune décision ne peut être présentée comme sans risque civil."},{"id":"f2","title":"Confirmation indépendante","result":"Une source extérieure confirme la présence récente de cadres, sans confirmer qu’ils sont encore regroupés."},{"id":"f3","title":"Situation des détenus","result":"La présence possible d’otages reste crédible et ne peut pas être écartée avant la décision finale."},{"id":"f4","title":"Chaîne de commandement","result":"Deux factions concurrentes existent. Frapper l’une ne revient pas automatiquement à neutraliser toute l’organisation."}],
 "expert_actions":[{"id":"e1","title":"Fiabilité des sources","result":"Les informations du troisième suspect sont souvent exactes mais anormalement concentrées sur une faction rivale."},{"id":"e2","title":"Présence du commandement","result":"La zone a hébergé des cadres récemment. La présence actuelle du noyau complet n’est pas démontrée."},{"id":"e3","title":"Risque civil","result":"Les données disponibles restent compatibles avec une présence civile et des détenus non évacués."}],
 "protected":[],"witnesses":[],"news":[],
 "truth":{"levels":[1,2,3],"summary":"Le premier suspect a soutenu politiquement le groupe et facilité des persécutions, mais n’était pas au cœur du commandement. Le deuxième a couvert des sévices graves dans l’appareil de détention. Le troisième est le responsable le plus lourdement impliqué et manipule l’enquête : il fournit beaucoup d’informations vraies pour pousser l’armée contre une faction rivale, pas pour faire triompher la vérité.","cinematic":{"turn":"Le mensonge décisif n’était pas une fausse information. C’était le choix soigneux des vérités que l’on vous donnait.","reframes":["Une coopération utile ne réduit pas automatiquement la responsabilité du troisième suspect.","La zone visée concentre réellement des cadres, mais elle ne représente pas à elle seule tout le commandement et des civils peuvent encore y être présents."],"timeline":["Deux factions du groupe entrent en conflit.","Le troisième suspect perd une partie de son influence.","Plusieurs cadres rivaux se regroupent temporairement dans une zone contestée.","Les trois suspects sont arrêtés.","Le troisième utilise sa coopération pour orienter l’attention militaire vers ses rivaux."],"characters":[{"slot":1,"place":"Relais politique local","anchors":"Responsabilité politique réelle mais secondaire dans la chaîne militaire.","hide":"Il a facilité persécutions et déplacements.","chronology":"Il cherche à sortir avant l’effondrement."},{"slot":2,"place":"Appareil de détention","anchors":"Il n’est pas le chef du réseau extérieur.","hide":"Il a couvert des sévices graves.","chronology":"Il coopère pour survivre."},{"slot":3,"place":"Cadre supérieur","anchors":"Ses informations sont souvent vraies.","hide":"Il veut utiliser la frappe contre ses rivaux.","chronology":"Sa coopération est une purge indirecte."}],"final_line":"Vous aviez besoin de vérité pour décider. Quelqu’un avait compris qu’une vérité sélectionnée pouvait être plus dangereuse qu’un mensonge."}}
}
$j$::jsonb),
('028',$j$
{
 "context":"Le dernier périmètre tient encore, mais une grande partie de la ville échappe aux autorités et les communications deviennent intermittentes. Une cellule intérieure est soupçonnée dans la zone protégée. Trois prisonniers sont interrogés. Deux comprennent que leur propre organisation les considère désormais comme sacrifiables ; le troisième semble attendre quelque chose.",
 "suspects":[
  {"place":"Tu as dirigé une structure locale avant d’être arrêté.","position":"Tu veux désormais coopérer parce que tu as compris que l’organisation ne te protégera pas. Tu veux sauver ta vie sans effacer ce que tu as fait.","anchors":"Tu as participé à des arrestations arbitraires et couvert des violences. Tu ne connais pas l’identité complète de la cellule intérieure.","hide":"Tu caches avoir longtemps cru que ton statut te protégerait, alors que tu avais déjà reçu des signes montrant le contraire.","chronology":"Tu exerces une autorité locale, puis tu es capturé. Lorsque les secteurs tombent, tu comprends que ton camp accepte ta mort avec celle des enquêteurs."},
  {"place":"Tu étais une source logistique de bas niveau devenue témoin de crimes que tu n’avais pas anticipés.","position":"Tu coopères sincèrement, mais tu minimises encore ton soutien antérieur au groupe. Tu veux que l’enquête distingue complicité et fanatisme.","anchors":"Tu n’as pas dirigé les violences. Tu connais toutefois une personne qui avait accès au périmètre protégé avant sa fermeture.","hide":"Tu caches avoir transmis pendant des mois des informations administratives qui ont ensuite servi à identifier certaines victimes.","chronology":"Tu aides d’abord le groupe sans participer directement aux violences, puis tu découvres comment tes informations sont utilisées. Tu cherches trop tard à t’en éloigner."},
  {"place":"Tu es un cadre fanatique resté fidèle jusqu’à l’arrestation.","position":"Tu ne cherches ni acquittement ni protection. Tu veux que l’enquête doute jusqu’au moment où le périmètre cède.","anchors":"Tu connais mieux que les autres l’existence de la cellule intérieure. Tu acceptes parfaitement que les prisonniers meurent si le groupe atteint le bâtiment.","hide":"Tu caches avoir validé le maintien d’une présence clandestine à l’intérieur du périmètre avant ta capture.","chronology":"Avant l’arrestation, tu sais qu’une présence intérieure doit survivre même si la ville est divisée. Pendant l’interrogatoire, tu attends de voir si elle existe encore."}
 ],
 "relations":{"1":[{"slot":2,"text":"Tu sais qu’il cherche réellement à coopérer, mais qu’il minimise ce qu’il a fourni au groupe."},{"slot":3,"text":"Son calme te terrifie : il semblait savoir avant vous que les prisonniers seraient sacrifiés."}],"2":[{"slot":1,"text":"Tu sais qu’il a couvert des violences locales."},{"slot":3,"text":"Tu l’as vu défendre le maintien d’une présence clandestine même après plusieurs arrestations."}],"3":[{"slot":1,"text":"Tu sais qu’il craquera si le périmètre se rapproche suffisamment."},{"slot":2,"text":"Tu connais la personne qu’il peut identifier, et tu espères qu’il parlera trop tard."}]},
 "role_notes":{"enqueteur":{"anchors":"Le temps presse, mais ton verdict reste une reconstruction de responsabilités. La survie ne transforme pas un aveu en vérité automatique."},"analyste":{"anchors":"Deux suspects peuvent coopérer sincèrement tout en restant responsables de crimes ou de complicités. Analyse les motivations sans les confondre avec l’innocence."},"expert":{"place":"Dans TERREUR, tu es l’Agent de renseignement.","position":"Tu cherches si une présence intérieure est plausible à partir de signaux indépendants.","anchors":"Une analyse par cycle. Aucun résultat ne donne un emplacement tactique ; tu confirmes seulement existence, crédibilité et liens."},"inspecteur":{"place":"Dans TERREUR, tu es l’Officier de liaison.","position":"Si tu es présent, tu maintiens la liaison avec la cellule de crise malgré les communications intermittentes.","anchors":"Tes actions servent à préserver les options de sortie et la continuité de l’enquête, jamais à diriger un combat."},"procureur":{"anchors":"Si tu es présent, la coopération de deux suspects peut être sincère sans effacer leur responsabilité antérieure."}},
 "trames":[
  {"title":"CAPITAINE — DÉCÉDÉ","text":"L’officier qui assurait une liaison extérieure est déclaré mort. La Grey Room perd un interlocuteur, pas sa mission.","kind":"balanced","min_cycle":1,"axes":["chronologie"]},
  {"title":"SOURCE INJOIGNABLE","text":"Une source située dans un secteur récemment perdu cesse de répondre. Son statut reste inconnu.","kind":"ambiguity","min_cycle":1,"axes":["chronologie"]},
  {"title":"ACCÈS ANTÉRIEUR","text":"Une personne liée au réseau avait un accès administratif au périmètre avant sa fermeture complète.","kind":"clarity","min_cycle":1,"axes":["acces"]},
  {"title":"PRISONNIERS SACRIFIABLES","text":"Un document interne indique que les membres capturés ne doivent plus être considérés comme récupérables.","kind":"clarity","min_cycle":1,"axes":["responsabilite"]},
  {"title":"COMMUNICATIONS INTERMITTENTES","text":"La Grey Room perd puis retrouve sa liaison extérieure. Plusieurs informations arrivent avec retard.","kind":"balanced","min_cycle":2,"axes":["chronologie"]},
  {"title":"COOPÉRATION CONCORDANTE","text":"Deux suspects donnent séparément des éléments compatibles sur la manière dont le groupe abandonne ses membres capturés.","kind":"clarity","min_cycle":2,"axes":["responsabilite"]},
  {"title":"LE TROISIÈME ATTEND","text":"Le troisième suspect ne demande ni protection ni évacuation malgré la dégradation du périmètre. Son calme n’établit rien, mais il contredit son récit de simple exécutant.","kind":"ambiguity","min_cycle":2,"axes":["mobile"]},
  {"title":"PRÉSENCE INTÉRIEURE PLAUSIBLE","text":"Plusieurs signaux indépendants rendent crédible l’existence d’une cellule clandestine déjà présente dans le périmètre avant sa fermeture.","kind":"clarity","min_cycle":3,"axes":["acces","responsabilite"]},
  {"title":"DÉCÈS CONFIRMÉ","text":"La source précédemment injoignable est désormais déclarée morte. L’information qu’elle devait confirmer devra être établie autrement.","kind":"balanced","min_cycle":3,"axes":["chronologie"]},
  {"title":"DERNIER PÉRIMÈTRE","text":"La protection extérieure atteint son niveau critique. L’enquête continue, mais aucune sortie ne peut plus être considérée comme garantie.","kind":"clarity","min_cycle":3,"axes":["responsabilite","chronologie"]}
 ],
 "field_actions":[{"id":"f1","title":"Maintenir la liaison","result":"Une liaison de crise reste disponible malgré plusieurs coupures. Elle ne garantit aucune évacuation."},{"id":"f2","title":"Recouper les statuts","result":"Plusieurs personnels sont confirmés hors de contact ; au moins un décès est établi."},{"id":"f3","title":"Vérifier le périmètre administratif","result":"Une autorisation antérieure a permis à une personne liée au réseau d’entrer avant le verrouillage complet."}],
 "expert_actions":[{"id":"e1","title":"Croiser les accès","result":"La présence intérieure est plausible et antérieure au dernier verrouillage du périmètre."},{"id":"e2","title":"Comparer les récits","result":"Les deux premiers suspects divergent sur leur propre responsabilité mais concordent sur l’abandon des prisonniers par l’organisation."},{"id":"e3","title":"Analyser les signaux","result":"Plusieurs signaux faibles convergent vers une cellule intérieure, sans révéler de position exploitable."},{"id":"e4","title":"Évaluer la crédibilité","result":"Le troisième suspect possède un niveau de connaissance incompatible avec le rôle secondaire qu’il revendique."}],
 "protected":[],"witnesses":[],"news":[],
 "truth":{"levels":[2,1,3],"summary":"Le premier suspect a exercé une autorité locale et couvert des violences, puis coopère réellement lorsqu’il comprend qu’il est sacrifiable. Le deuxième a fourni des informations administratives utilisées contre des victimes mais n’a pas dirigé les crimes et coopère sincèrement. Le troisième est le cadre le plus dangereux : il a validé le maintien d’une présence clandestine à l’intérieur du périmètre et accepte sa propre mort si l’organisation parvient à faire tomber la Grey Room.","cinematic":{"turn":"Deux suspects parlaient parce qu’ils avaient peur de mourir. Le troisième se taisait parce que cette perspective ne constituait pas une menace pour lui.","reframes":["La coopération des deux premiers n’efface pas leurs responsabilités réelles.","Le calme du troisième n’était jamais une preuve ; les accès et les communications établissent finalement ce que son comportement ne pouvait qu’évoquer."],"timeline":["Une présence clandestine est maintenue avant la fermeture du périmètre.","Les trois suspects sont capturés.","La ville perd plusieurs secteurs.","L’organisation déclare ses prisonniers sacrifiables.","Les indices sur la cellule intérieure convergent alors que le périmètre atteint un niveau critique."],"characters":[{"slot":1,"place":"Responsable local","anchors":"Violences couvertes, coopération tardive mais réelle.","hide":"Il avait déjà compris qu’il serait abandonné.","chronology":"Il craque lorsque le périmètre se dégrade."},{"slot":2,"place":"Soutien administratif","anchors":"Complicité réelle mais responsabilité moindre.","hide":"Ses données ont servi contre des victimes.","chronology":"Il coopère sincèrement après avoir compris l’usage de ses informations."},{"slot":3,"place":"Cadre fanatique","anchors":"Connaissance centrale de la cellule intérieure.","hide":"Il a validé son maintien.","chronology":"Il attend la rupture du périmètre sans demander à être sauvé."}],"final_line":"Le dernier périmètre n’était pas seulement une ligne autour du bâtiment. C’était le temps qu’il restait pour comprendre qui, parmi vous, voulait encore sortir vivant."}}
}
$j$::jsonb)
on conflict (scenario_id) do update set pack=excluded.pack;

create or replace function public.igr_v4_min_players(p_scenario text)
returns integer language sql immutable set search_path to 'public' as $$
 select case when p_scenario in ('021','022','023','024','025') then 4 when p_scenario='026' then 6 when p_scenario='027' then 7 when p_scenario='028' then 6 when p_scenario in ('001','003','004','005','006') then 4 when p_scenario='002' then 5 when p_scenario in ('007','008','009','010','011','012','013','014','015','016') then 5 when p_scenario='017' then 7 when p_scenario='018' then 6 when p_scenario='019' then 9 when p_scenario='020' then 13 else 5 end
$$;

create or replace function public.igr_v4_max_players(p_scenario text)
returns integer language sql immutable set search_path to 'public' as $$
 select case when p_scenario in ('021','022','023','024','025') then 8 when p_scenario='026' then 7 when p_scenario='027' then 8 when p_scenario='028' then 8 when p_scenario in ('001','003','004','005','006') then 5 when p_scenario='002' then 6 when p_scenario in ('007','008','009','010','011','012') then 5 when p_scenario in ('013','014') then 6 when p_scenario='015' then 7 when p_scenario='016' then 8 when p_scenario='017' then 8 when p_scenario='018' then 6 when p_scenario='019' then 9 when p_scenario='020' then 16 else 5 end
$$;

create or replace function public.igr_v4_role_for_seat(p_scenario text,p_seat integer,p_count integer)
returns text language plpgsql immutable set search_path to 'public' as $$
begin
 if p_scenario='026' then
  if p_count=6 then return (array['enqueteur','analyste','expert','suspect','suspect','suspect'])[p_seat+1]; else return (array['enqueteur','analyste','expert','procureur','suspect','suspect','suspect'])[p_seat+1]; end if;
 elsif p_scenario='027' then
  if p_count=7 then return (array['enqueteur','analyste','procureur','inspecteur','suspect','suspect','suspect'])[p_seat+1]; else return (array['enqueteur','analyste','procureur','inspecteur','expert','suspect','suspect','suspect'])[p_seat+1]; end if;
 elsif p_scenario='028' then
  if p_count=6 then return (array['enqueteur','analyste','expert','suspect','suspect','suspect'])[p_seat+1]; elsif p_count=7 then return (array['enqueteur','analyste','expert','inspecteur','suspect','suspect','suspect'])[p_seat+1]; else return (array['enqueteur','analyste','expert','inspecteur','procureur','suspect','suspect','suspect'])[p_seat+1]; end if;
 elsif p_scenario in ('001','003','004','005','006') then if p_seat=0 then return 'enqueteur'; elsif p_count=5 and p_seat=1 then return 'analyste'; else return 'suspect'; end if;
 elsif p_scenario='002' then if p_seat=0 then return 'enqueteur'; elsif p_count=6 and p_seat=1 then return 'analyste'; else return 'suspect'; end if;
 elsif p_scenario in ('007','008','009','010','011','012') then return (array['enqueteur','analyste','suspect','suspect','suspect'])[p_seat+1];
 elsif p_scenario='013' then return (array['enqueteur','analyste','suspect','suspect','suspect','procureur'])[p_seat+1];
 elsif p_scenario='014' then return (array['enqueteur','analyste','suspect','suspect','suspect','juge'])[p_seat+1];
 elsif p_scenario='015' then return (array['enqueteur','analyste','suspect','suspect','suspect','journaliste','juge'])[p_seat+1];
 elsif p_scenario='016' then return (array['enqueteur','analyste','suspect','suspect','suspect','maitre','journaliste','juge'])[p_seat+1];
 elsif p_scenario='017' then return (array['enqueteur','analyste','procureur','suspect','suspect','suspect','temoin','temoin'])[p_seat+1];
 elsif p_scenario='018' then return (array['enqueteur','analyste','inspecteur','suspect','suspect','suspect'])[p_seat+1];
 elsif p_scenario='019' then return (array['enqueteur','analyste','procureur','juge','journaliste','maitre','suspect','suspect','suspect'])[p_seat+1];
 elsif p_scenario='020' then return (array['enqueteur','analyste','inspecteur','procureur','juge','expert','suspect','suspect','suspect','suspect','maitre','journaliste','temoin','maitre','journaliste','temoin'])[p_seat+1]; end if;
 return 'suspect';
end $$;

create or replace function public.igr_v4_role_capacity(p_scenario text,p_count integer,p_role text)
returns integer language plpgsql immutable set search_path to 'public' as $$
declare r text:=lower(trim(coalesce(p_role,'')));
begin
 if r='avocat' then r:='maitre'; end if;
 if r='enqueteur' then return 1;
 elsif r='analyste' then return case when p_scenario in ('001','003','004','005','006') and p_count=4 then 0 else 1 end;
 elsif r='suspect' then return case when p_scenario='002' then 4 when p_scenario='020' then 4 else 3 end;
 elsif r='procureur' then return case when p_scenario in ('017','019','020','027') then 1 when p_scenario='013' and p_count>=6 then 1 when p_scenario='026' and p_count>=7 then 1 when p_scenario='028' and p_count>=8 then 1 else 0 end;
 elsif r='juge' then return case when p_scenario in ('019','020') then 1 when p_scenario='014' and p_count>=6 then 1 when p_scenario='015' and p_count>=7 then 1 when p_scenario='016' and p_count>=8 then 1 else 0 end;
 elsif r='journaliste' then return case when p_scenario='019' then 1 when p_scenario='020' then case when p_count>=15 then 2 else 1 end when p_scenario='015' and p_count>=6 then 1 when p_scenario='016' and p_count>=7 then 1 else 0 end;
 elsif r='maitre' then return case when p_scenario='019' then 1 when p_scenario='020' then case when p_count>=14 then 2 else 1 end when p_scenario='016' and p_count>=6 then 1 else 0 end;
 elsif r='inspecteur' then return case when p_scenario in ('018','020','027') then 1 when p_scenario='028' and p_count>=7 then 1 else 0 end;
 elsif r='expert' then return case when p_scenario in ('020','026','028') then 1 when p_scenario='027' and p_count>=8 then 1 else 0 end;
 elsif r='temoin' then return case when p_scenario='017' then case when p_count>=8 then 2 else 1 end when p_scenario='020' then case when p_count>=16 then 2 else 1 end else 0 end; end if;
 return 0;
end $$;

create or replace function public.igr_v4_choose_role(p_code text,p_player_token uuid,p_role text)
returns jsonb language plpgsql security definer set search_path to 'public' as $$
declare p public.igr_v4_players%rowtype; r public.igr_v4_rooms%rowtype; c int; cap int:=0; taken int:=0;
begin
 select * into p from public.igr_v4_players where room_code=upper(trim(p_code)) and player_token=p_player_token; if not found then raise exception 'unauthorized'; end if;
 select * into r from public.igr_v4_rooms where code=p.room_code for update; if r.status<>'lobby' then raise exception 'game already started'; end if;
 if r.scenario_id in ('021','022','023','024','025') then return public.igr_omerta_choose_role(p_code,p_player_token,p_role); end if;
 p_role:=lower(trim(coalesce(p_role,''))); if p_role in ('','none','annuler','cancel') then update public.igr_v4_players set preferred_role=null where id=p.id; return jsonb_build_object('ok',true,'role',null,'cleared',true); end if; if p_role='avocat' then p_role:='maitre'; end if;
 select count(*) into c from public.igr_v4_players where room_code=r.code; cap:=public.igr_v4_role_capacity(r.scenario_id,c,p_role); if cap<=0 then raise exception 'role unavailable'; end if;
 select count(*) into taken from public.igr_v4_players where room_code=r.code and id<>p.id and preferred_role=p_role; if taken>=cap then raise exception 'role already taken'; end if;
 update public.igr_v4_players set preferred_role=p_role where id=p.id; return jsonb_build_object('ok',true,'role',p_role,'cleared',false);
end $$;

create or replace function public.igr_v4_choose_random_role(p_code text,p_player_token uuid)
returns jsonb language plpgsql security definer set search_path to 'public' as $$
declare p public.igr_v4_players%rowtype; r public.igr_v4_rooms%rowtype; player_count int; picked text;
begin
 select * into p from public.igr_v4_players where room_code=upper(trim(p_code)) and player_token=p_player_token; if not found then raise exception 'unauthorized'; end if;
 select * into r from public.igr_v4_rooms where code=p.room_code for update; if not found then raise exception 'room not found'; end if; if r.status<>'lobby' then raise exception 'game already started'; end if;
 select count(*) into player_count from public.igr_v4_players where room_code=r.code;
 if r.scenario_id in ('021','022','023','024','025') then
  select q.role into picked from (values ('enqueteur'),('analyste'),('suspect'),('associato'),('uomo_onore'),('contabile'),('caporegime'),('consigliere'),('pentito'),('sottocapo'),('don')) q(role) where public.igr_omerta_role_allowed(r.scenario_id,q.role) and (select count(*) from public.igr_v4_players x where x.room_code=r.code and x.id<>p.id and x.preferred_role=q.role)<case when q.role='suspect' then 7 else 1 end order by gen_random_uuid() limit 1;
 else
  select q.role into picked from (values ('enqueteur'),('analyste'),('suspect'),('procureur'),('juge'),('journaliste'),('maitre'),('inspecteur'),('expert'),('temoin')) q(role) where public.igr_v4_role_capacity(r.scenario_id,player_count,q.role)>0 and (select count(*) from public.igr_v4_players x where x.room_code=r.code and x.id<>p.id and x.preferred_role=q.role)<public.igr_v4_role_capacity(r.scenario_id,player_count,q.role) order by gen_random_uuid() limit 1; end if;
 if picked is null then raise exception 'no role available'; end if; update public.igr_v4_players set preferred_role=picked where id=p.id; return jsonb_build_object('ok',true,'role',picked,'scenario_id',r.scenario_id,'player_count',player_count);
end $$;

create or replace function public.igr_terror_perimeter_value(p_scenario text,p_cycle integer)
returns integer language sql immutable set search_path to 'public' as $$
 select case p_scenario when '026' then case when p_cycle<=0 then 82 when p_cycle=1 then 66 when p_cycle=2 then 43 else 21 end when '027' then case when p_cycle<=0 then 88 when p_cycle=1 then 74 when p_cycle=2 then 56 else 38 end when '028' then case when p_cycle<=0 then 64 when p_cycle=1 then 44 when p_cycle=2 then 25 else 12 end else 100 end
$$;

create or replace function public.igr_terror_room_state()
returns trigger language plpgsql set search_path to 'public' as $$
declare t jsonb; p int;
begin
 if new.scenario_id not in ('026','027','028') then return new; end if; p:=public.igr_terror_perimeter_value(new.scenario_id,new.cycle); t:=coalesce(new.state->'terror','{}'::jsonb); t:=t||jsonb_build_object('enabled',true,'perimeter',p,'band',case when p<=20 then 'CRITIQUE' when p<=45 then 'FRAGILE' when p<=70 then 'CONTESTÉ' else 'SOUS CONTRÔLE' end); new.state:=jsonb_set(coalesce(new.state,'{}'::jsonb),'{terror}',t,true); return new;
end $$;

drop trigger if exists igr_terror_room_state_trg on public.igr_v4_rooms;
create trigger igr_terror_room_state_trg before update of status,cycle,state on public.igr_v4_rooms for each row execute function public.igr_terror_room_state();

create or replace function public.igr_terror_emit_perimeter()
returns trigger language plpgsql set search_path to 'public' as $$
declare p int; msg text;
begin
 if new.scenario_id not in ('026','027','028') or new.status<>'playing' then return new; end if; if not (old.status is distinct from new.status or old.cycle is distinct from new.cycle) then return new; end if; p:=public.igr_terror_perimeter_value(new.scenario_id,new.cycle);
 msg:=case new.scenario_id when '026' then case new.cycle when 0 then 'La ville tient encore, mais plusieurs secteurs sont contestés.' when 1 then 'Un nouveau secteur est perdu. Les autorités réduisent leur zone garantie.' when 2 then 'Les communications extérieures deviennent irrégulières. La Grey Room n’est plus loin de la zone de rupture.' else 'Le périmètre est critique. La protection du bâtiment n’est plus considérée comme durable.' end when '027' then case new.cycle when 0 then 'La zone contestée reste partiellement isolée. L’évacuation civile est incomplète.' when 1 then 'Les informations sur le commandement restent contradictoires.' when 2 then 'La fenêtre de décision se réduit tandis que civils et détenus restent possibles dans la zone.' else 'Le verdict devra être assez solide pour soutenir une décision militaire irréversible.' end else case new.cycle when 0 then 'Le dernier périmètre tient, mais plusieurs liaisons sont déjà intermittentes.' when 1 then 'Des personnels passent hors contact. Les prisonniers comprennent que personne ne garantit leur extraction.' when 2 then 'Une présence intérieure devient plausible tandis que les secteurs extérieurs continuent de tomber.' else 'Aucune sortie n’est désormais garantie. L’enquête entre dans son dernier cycle.' end end;
 insert into public.igr_v4_events(room_code,event_type,payload) values(new.code,'phase',jsonb_build_object('title','PÉRIMÈTRE · '||p||' %','text',msg)); return new;
end $$;

drop trigger if exists igr_terror_emit_perimeter_trg on public.igr_v4_rooms;
create trigger igr_terror_emit_perimeter_trg after update of status,cycle on public.igr_v4_rooms for each row execute function public.igr_terror_emit_perimeter();

create or replace function public.igr_terror_military_decision(p_code text,p_player_token uuid,p_decision text)
returns jsonb language plpgsql security definer set search_path to 'public' as $$
declare p public.igr_v4_players%rowtype; r public.igr_v4_rooms%rowtype; pack jsonb; enq public.igr_v4_players%rowtype; a jsonb; s public.igr_v4_players%rowtype; truth_levels jsonb; truth int; guess int; exact int:=0; total int:=0; outcome text; t jsonb;
begin
 select * into p from public.igr_v4_players where room_code=upper(trim(p_code)) and player_token=p_player_token; if not found then raise exception 'unauthorized'; end if; select * into r from public.igr_v4_rooms where code=p.room_code for update;
 if r.scenario_id<>'027' or p.public_role<>'inspecteur' then raise exception 'forbidden'; end if; if r.status<>'finished' or r.phase<>'reveal' then raise exception 'decision available after verdict'; end if; if coalesce(r.state->'terror'->>'military_decision','')<>'' then raise exception 'already decided'; end if;
 p_decision:=lower(trim(coalesce(p_decision,''))); if p_decision not in ('intervene','delay','cancel') then raise exception 'invalid decision'; end if;
 select x.pack into pack from public.igr_v4_scenario_packs x where x.scenario_id='027'; truth_levels:=pack->'truth'->'levels'; select * into enq from public.igr_v4_players where room_code=r.code and public_role='enqueteur' limit 1; select payload->'levels' into a from public.igr_v4_actions where room_code=r.code and player_id=enq.id and action_type='final_lock' order by id desc limit 1; a:=coalesce(a,'{}'::jsonb);
 for s in select * from public.igr_v4_players where room_code=r.code and public_role='suspect' order by internal_slot loop truth:=coalesce((truth_levels->>(s.internal_slot-1))::int,0); guess:=coalesce((a->>s.id::text)::int,-1); total:=total+1; if truth=guess then exact:=exact+1; end if; end loop;
 if p_decision='intervene' then if exact=total then outcome:='La frappe est autorisée sur la base d’un verdict exact. Le noyau visé est effectivement touché, mais l’évacuation était incomplète : des victimes civiles sont confirmées. La décision reste militairement efficace et moralement lourde.'; else outcome:='La frappe est autorisée alors que le verdict comporte encore une erreur. Des victimes civiles sont confirmées et le noyau recherché n’était pas entièrement présent. L’enquête comprend trop tard qu’une faction l’a utilisée contre ses rivaux.'; end if;
 elsif p_decision='delay' then if exact=total then outcome:='L’intervention est différée. Une partie supplémentaire des civils peut quitter la zone, mais plusieurs cadres profitent du délai pour se disperser. Le verdict était juste ; le choix a privilégié la réduction du risque civil.'; else outcome:='L’intervention est différée. Ce délai fait apparaître une contradiction dans le renseignement et évite une décision fondée sur un verdict incomplet, mais une partie du réseau se disperse.'; end if;
 else if exact=total then outcome:='La frappe est annulée malgré un verdict exact. Le risque immédiat pour les civils lié à cette intervention est écarté, mais le noyau de commandement se disperse et reste partiellement actif.'; else outcome:='La frappe est annulée. Le verdict incomplet n’est pas transformé en décision irréversible ; la zone n’est pas frappée, mais l’organisation conserve une partie de sa capacité de commandement.'; end if; end if;
 t:=coalesce(r.state->'terror','{}'::jsonb)||jsonb_build_object('military_decision',p_decision,'military_outcome',outcome,'verdict_exact',exact,'verdict_total',total); update public.igr_v4_rooms set state=jsonb_set(coalesce(state,'{}'::jsonb),'{terror}',t,true),updated_at=now() where code=r.code; insert into public.igr_v4_events(room_code,event_type,payload) values(r.code,'phase',jsonb_build_object('title','DÉCISION MILITAIRE','text',outcome)); return jsonb_build_object('ok',true,'decision',p_decision,'outcome',outcome,'accuracy',jsonb_build_object('exact',exact,'total',total));
end $$;

revoke all on function public.igr_terror_military_decision(text,uuid,text) from public;
grant execute on function public.igr_terror_military_decision(text,uuid,text) to anon,authenticated;
